#!/bin/sh

### BEGIN INIT INFO
# Provides:          qemu-guest-agent
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: QEMU Guest Agent
# Description:       QEMU Guest Agent
### END INIT INFO

DAEMON=/usr/sbin/qemu-ga
PIDFILE=/var/run/qemu-ga.pid

test -x $DAEMON || exit 0

case "$1" in
    start)
        echo -n "Starting QEMU Guest Agent: qemu-ga"
        start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --startas $DAEMON
        echo "."
        ;;
    stop)
        echo -n "Stopping QEMU Guest Agent: qemu-ga"
        start-stop-daemon --stop --pidfile $PIDFILE --retry 10
        echo "."
        ;;
    restart)
        echo -n "Restarting QEMU Guest Agent: qemu-ga"
        start-stop-daemon --stop --pidfile $PIDFILE --retry 10
        start-stop-daemon --start --background --pidfile $PIDFILE --make-pidfile --startas $DAEMON
        echo "."
        ;;
    *)
        echo "Usage: /etc/init.d/qemu-guest-agent {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
